name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fingineerwebapp
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: fingineerwebapp/package-lock.json

      - name: Install dependencies (try npm ci, fall back to npm install)
        run: npm ci || npm install

      - name: Lint
        run: npm run lint --if-present

      - name: Build (temporarily allow warnings)
        run: CI=false npm run build --if-present
