name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

New-Item -ItemType Directory -Force .github\workflows

@"
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint (если есть)
        run: npm run lint --if-present

      - name: Test (если есть)
        run: npm test --if-present

      - name: Build (если есть)
        run: npm run build --if-present
